# MangoWM autostart modules

exec-once=~/.config/quickshell/bar/reload.sh
exec-once=awww-daemon
exec-once=wl-paste --type text/plain --watch cliphist store
exec-once=wl-paste --type image --watch cliphist store
exec-once=swayidle -w -C ~/.config/mango/swayidle.conf
exec-once=swaync
exec-once=blueman-applet
exec-once=nm-applet --indicator
exec-once=~/edots/run.sh
exec-once=python3 ~/edots/tui-player/forks/player.py -d
