# ~/.config/fish/config.fish

# --- Disable Welcome Greeting ---
set -g fish_greeting

# --- 1. Load Dynamic Colors generated by wallcolors.py ---
if test -f "$HOME/.config/fish/fish-colors.fish"
    source "$HOME/.config/fish/fish-colors.fish"
else if test -f "$HOME/.config/quickshell/colors.json"; and type -q jq
    # Fallback to JSON parsing if fish-colors.fish is not created yet
    set -gx COLOR_ACCENT (jq -r '.accent // "#00f5d4"' "$HOME/.config/quickshell/colors.json")
    set -gx COLOR_FG (jq -r '.fg // "#e0e0e0"' "$HOME/.config/quickshell/colors.json")
    set -gx COLOR_BG0 (jq -r '.bg0 // "#101010"' "$HOME/.config/quickshell/colors.json")
    set -gx COLOR_PURPLE (jq -r '.purple // "#7b2cbf"' "$HOME/.config/quickshell/colors.json")
    set -gx COLOR_BLUE (jq -r '.blue // "#00b4d8"' "$HOME/.config/quickshell/colors.json")
    set -gx COLOR_GREEN (jq -r '.green // "#00f5d4"' "$HOME/.config/quickshell/colors.json")
    set -gx COLOR_RED (jq -r '.red // "#ff0055"' "$HOME/.config/quickshell/colors.json")
end

# --- 2. Initialize Starship Prompt ---
if type -q starship
    starship init fish | source
end

# --- 3. Package Management Aliases ---
alias i='upkg install'
alias ps='upkg search'

# --- 4. Navigation & Directory Aliases ---
alias ..='cd ..'
alias .='cd ~'
alias r='cd /'
alias w='cd ~/coderP/'
alias ew='e ~/coderP/'
alias eq='e ~/.config/quickshell/'
alias eb='e ~/.config/fish/config.fish'
alias ee='e ~/edots/'
alias em='e ~/.config/mango'
alias ff='fastfetch'

# --- 5. System & Utility Aliases ---
alias e='nvim'
alias ct='clear; and tree'
alias susp='systemctl suspend'
alias mk='mkdir -p'
alias rm='rm -r'
alias c='clear'

alias grep='grep --color=auto'
alias ls='ls -la --group-directories-first --color=auto'

# --- 6. Fastfetch on Startup ---
if type -q fastfetch
    fastfetch
end

# pnpm
set -gx PNPM_HOME "$HOME/.local/share/pnpm"
if not string match -q -- "$PNPM_HOME/bin" $PATH
    set -gx PATH "$PNPM_HOME/bin" $PATH
end
# pnpm end

# Created by `pipx` on 2026-09-11 08:17:07
set PATH $PATH /home/eduard/.local/bin
set -gx BROWSER /usr/bin/firefox
